import type { WatchlistItem } from "@/lib/watchlist";

export const DEV_MOCK_DATA: WatchlistItem[] = [
  // ── ATIVOS ORIGINAIS (8) ────────────────────────────────────────────────────

  {
    id: "brazilian_stock:BBAS3",
    ticker: "BBAS3",
    name: "Banco do Brasil S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 26.5,
    annualDividend: 2.8,
    targetYield: 6,
    ceilingPrice: 46.66,
    safetyMargin: 76.1,
    quantity: 1000,
    averagePrice: 22.0,
    paymentMonths: [2, 3, 5, 6, 8, 9, 11, 12],
    payoutRatio: 40,
    targetMonthlyIncome: 1000,
    addedAt: Date.now(),
    investingSince: new Date("2026-02-01T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    id: "brazilian_stock:TEST_IPO_RECENTE",
    ticker: "TEST_IPO_RECENTE",
    name: "Synthetic Recent IPO",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 15.0,
    annualDividend: 1.5,
    targetYield: 6,
    ceilingPrice: 25.0,
    safetyMargin: 66.6,
    quantity: 500,
    averagePrice: 12.0,
    paymentMonths: [4, 10],
    payoutRatio: 50,
    targetMonthlyIncome: 500,
    addedAt: Date.now(),
    investingSince: new Date("2026-01-15T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Utilities",
  },
  {
    id: "fii:KNCR11",
    ticker: "KNCR11",
    name: "Kinea Rendimentos Imobiliários",
    type: "FII",
    currency: "BRL",
    currentPrice: 105.0,
    annualDividend: 12.5,
    targetYield: 10,
    ceilingPrice: 125.0,
    safetyMargin: 19.0,
    quantity: 200,
    averagePrice: 98.5,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 500,
    addedAt: Date.now(),
    investingSince: new Date("2026-04-10T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    id: "reit:O",
    ticker: "O",
    name: "Realty Income Corporation",
    type: "REIT",
    currency: "USD",
    currentPrice: 55.0,
    annualDividend: 3.1,
    targetYield: 4,
    ceilingPrice: 77.5,
    safetyMargin: 40.9,
    quantity: 100,
    averagePrice: 50.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: 75,
    targetMonthlyIncome: 100,
    addedAt: Date.now(),
    investingSince: new Date("2026-05-20T12:00:00Z").getTime(),
    customTaxRate: 30,
    sector: "Real Estate",
  },
  {
    id: "us_stock:MSFT",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    type: "STOCK_US",
    currency: "USD",
    currentPrice: 420.0,
    annualDividend: 3.0,
    targetYield: 2,
    ceilingPrice: 150.0,
    safetyMargin: -64.2,
    quantity: 50,
    averagePrice: 200.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: 25,
    targetMonthlyIncome: 50,
    addedAt: Date.now(),
    investingSince: new Date("2026-06-05T12:00:00Z").getTime(),
    customTaxRate: 30,
    sector: "Technology",
  },
  {
    id: "etf:IVVB11",
    ticker: "IVVB11",
    name: "iShares S&P 500 Fundo de Investimento",
    type: "ETF",
    currency: "BRL",
    currentPrice: 280.0,
    annualDividend: 0,
    targetYield: 0,
    ceilingPrice: 0,
    safetyMargin: 0,
    quantity: 100,
    averagePrice: 250.0,
    paymentMonths: [],
    payoutRatio: null,
    targetMonthlyIncome: null,
    addedAt: Date.now(),
    investingSince: new Date("2025-02-15T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    id: "fii_infra:BDIF11",
    ticker: "BDIF11",
    name: "BTG Pactual Dívida Infra",
    type: "FII_INFRA",
    currency: "BRL",
    currentPrice: 95.0,
    annualDividend: 12.0,
    targetYield: 11,
    ceilingPrice: 109.09,
    safetyMargin: 14.8,
    quantity: 300,
    averagePrice: 90.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 400,
    addedAt: Date.now(),
    investingSince: new Date("2025-06-12T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Infrastructure",
  },
  {
    id: "fiagro:SNAG11",
    ticker: "SNAG11",
    name: "Suno Agro Fiagro",
    type: "FIAGRO",
    currency: "BRL",
    currentPrice: 10.15,
    annualDividend: 1.3,
    targetYield: 12,
    ceilingPrice: 10.83,
    safetyMargin: 6.7,
    quantity: 1000,
    averagePrice: 10.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 150,
    addedAt: Date.now(),
    investingSince: new Date("2025-08-22T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Agriculture",
  },

  // ── NOVOS ATIVOS BR (6) — cobre Ação, FII e FII-Infra variados ─────────────

  {
    // Grande ação BR com pagamento semestral concentrado em Jun/Dez.
    // Stresses o gráfico com picos grandes em dois meses específicos.
    id: "brazilian_stock:VALE3",
    ticker: "VALE3",
    name: "Vale S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 62.0,
    annualDividend: 7.8,
    targetYield: 8,
    ceilingPrice: 97.5,
    safetyMargin: 57.3,
    quantity: 800,
    averagePrice: 55.0,
    paymentMonths: [6, 12],
    payoutRatio: 55,
    targetMonthlyIncome: 800,
    addedAt: Date.now(),
    investingSince: new Date("2025-10-30T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Materials",
  },
  {
    // Ação BR com pagamento trimestral menos usual (Jan/Abr/Jul/Out).
    // Cria dispersão diferente dos outros ativos trimestrais.
    id: "brazilian_stock:ITUB4",
    ticker: "ITUB4",
    name: "Itaú Unibanco Holding S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 38.5,
    annualDividend: 2.2,
    targetYield: 5,
    ceilingPrice: 44.0,
    safetyMargin: 14.3,
    quantity: 600,
    averagePrice: 32.0,
    paymentMonths: [1, 4, 7, 10],
    payoutRatio: 45,
    targetMonthlyIncome: 300,
    addedAt: Date.now(),
    investingSince: new Date("2025-11-15T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    // FII tijolo de alto DY com pagamento mensal. Grande posição para
    // testar dominância no terceiro gráfico (Investido vs. Recebido).
    id: "fii:MXRF11",
    ticker: "MXRF11",
    name: "Maxi Renda FII",
    type: "FII",
    currency: "BRL",
    currentPrice: 10.3,
    annualDividend: 1.44,
    targetYield: 12,
    ceilingPrice: 12.0,
    safetyMargin: 16.5,
    quantity: 3000,
    averagePrice: 9.8,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 360,
    addedAt: Date.now(),
    investingSince: new Date("2024-03-01T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    // FII de papel (CRI) com pagamento mensal e yield alto.
    // Segunda maior posição em BRL — boa pressão no top-10.
    id: "fii:CPTS11",
    ticker: "CPTS11",
    name: "Capitânia Securities FII",
    type: "FII",
    currency: "BRL",
    currentPrice: 8.6,
    annualDividend: 1.2,
    targetYield: 13,
    ceilingPrice: 9.23,
    safetyMargin: 7.3,
    quantity: 2500,
    averagePrice: 8.2,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 250,
    addedAt: Date.now(),
    investingSince: new Date("2024-05-18T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    // FII-Infra com pagamento mensal e DY elevado.
    // Adiciona diversidade de tipo junto ao BDIF11 já existente.
    id: "fii_infra:IFRA11",
    ticker: "IFRA11",
    name: "iShares Infraestrutura FII",
    type: "FII_INFRA",
    currency: "BRL",
    currentPrice: 118.0,
    annualDividend: 14.4,
    targetYield: 11,
    ceilingPrice: 130.9,
    safetyMargin: 10.9,
    quantity: 150,
    averagePrice: 110.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 200,
    addedAt: Date.now(),
    investingSince: new Date("2024-07-22T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Infrastructure",
  },
  {
    // Ação BR de energia com pagamento bianual (Mar/Set).
    // Cria picos de valor real a cada semestre num padrão diferente das anteriores.
    id: "brazilian_stock:EGIE3",
    ticker: "EGIE3",
    name: "Engie Brasil Energia S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 44.0,
    annualDividend: 4.2,
    targetYield: 8,
    ceilingPrice: 52.5,
    safetyMargin: 19.3,
    quantity: 400,
    averagePrice: 38.0,
    paymentMonths: [3, 9],
    payoutRatio: 60,
    targetMonthlyIncome: 200,
    addedAt: Date.now(),
    investingSince: new Date("2024-09-10T12:00:00Z").getTime(),
    customTaxRate: null,
    sector: "Utilities",
  },

  // ── NOVOS ATIVOS US (4) — REITs mensais e ações trimestrais ─────────────────

  {
    // REIT mensal de escritórios — complementa Realty Income na moeda USD.
    // Contribuição mensal estável mas menor que O, gerando mistura de barras.
    id: "reit:STAG",
    ticker: "STAG",
    name: "STAG Industrial REIT",
    type: "REIT",
    currency: "USD",
    currentPrice: 35.0,
    annualDividend: 1.56,
    targetYield: 4.5,
    ceilingPrice: 34.67,
    safetyMargin: -0.9,
    quantity: 120,
    averagePrice: 30.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: 80,
    targetMonthlyIncome: 60,
    addedAt: Date.now(),
    investingSince: new Date("2024-12-05T12:00:00Z").getTime(),
    customTaxRate: 30,
    sector: "Real Estate",
  },
  {
    // Blue chip US com DY baixo mas pagamento trimestral consistente.
    // Testa o corte top-10 no terceiro gráfico (investido alto, recebido baixo).
    id: "us_stock:JNJ",
    ticker: "JNJ",
    name: "Johnson & Johnson",
    type: "STOCK_US",
    currency: "USD",
    currentPrice: 155.0,
    annualDividend: 4.76,
    targetYield: 3,
    ceilingPrice: 158.67,
    safetyMargin: 2.4,
    quantity: 40,
    averagePrice: 140.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: 45,
    targetMonthlyIncome: 50,
    addedAt: Date.now(),
    investingSince: new Date("2023-01-15T12:00:00Z").getTime(),
    customTaxRate: 30,
    sector: "Healthcare",
  },
  {
    // REIT de saúde — pagamento trimestral, DY razoável.
    // Junto com STAG cria dois tipos de REIT na carteira US.
    id: "reit:MPW",
    ticker: "MPW",
    name: "Medical Properties Trust",
    type: "REIT",
    currency: "USD",
    currentPrice: 5.5,
    annualDividend: 0.6,
    targetYield: 8,
    ceilingPrice: 7.5,
    safetyMargin: 36.4,
    quantity: 300,
    averagePrice: 8.0,
    paymentMonths: [1, 4, 7, 10],
    payoutRatio: 85,
    targetMonthlyIncome: 45,
    addedAt: Date.now(),
    investingSince: new Date("2023-06-20T12:00:00Z").getTime(),
    customTaxRate: 30,
    sector: "Real Estate",
  },
  {
    // ETF US de dividendos — pagamento trimestral, exposição ampla.
    // Stresses o gráfico US com um contribuidor menor mas presente em 4 meses.
    id: "etf:VYM",
    ticker: "VYM",
    name: "Vanguard High Dividend Yield ETF",
    type: "ETF",
    currency: "USD",
    currentPrice: 120.0,
    annualDividend: 3.6,
    targetYield: 3,
    ceilingPrice: 120.0,
    safetyMargin: 0.0,
    quantity: 60,
    averagePrice: 105.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: null,
    targetMonthlyIncome: 54,
    addedAt: Date.now(),
    investingSince: new Date("2022-04-10T12:00:00Z").getTime(),
    customTaxRate: 30,
    sector: "Diversified",
  },
];

import type { Transaction } from "@/lib/transactionsLogic";

export const DEV_MOCK_TRANSACTIONS: Transaction[] = [
  // BBAS3 (Qty: 1000, PM: 22.0)
  {
    id: "tx-bbas3-1",
    ticker: "BBAS3",
    type: "buy",
    date: new Date("2024-02-15T10:00:00Z").getTime(),
    quantity: 500,
    pricePerShare: 20.0,
    fees: 0,
    notes: "Aporte inicial",
  },
  {
    id: "tx-bbas3-2",
    ticker: "BBAS3",
    type: "buy",
    date: new Date("2024-08-10T10:00:00Z").getTime(),
    quantity: 500,
    pricePerShare: 24.0,
    fees: 0,
    notes: "Reinvestimento dividendos",
  },

  // VALE3 (Qty: 800, PM: 55.0)
  {
    id: "tx-vale3-1",
    ticker: "VALE3",
    type: "buy",
    date: new Date("2024-01-20T10:00:00Z").getTime(),
    quantity: 400,
    pricePerShare: 52.0,
    fees: 0,
    notes: "Aporte regular",
  },
  {
    id: "tx-vale3-2",
    ticker: "VALE3",
    type: "buy",
    date: new Date("2024-06-15T10:00:00Z").getTime(),
    quantity: 400,
    pricePerShare: 58.0,
    fees: 0,
    notes: "Aporte adicional",
  },

  // ITUB4 (Qty: 600, PM: 32.0)
  {
    id: "tx-itub4-1",
    ticker: "ITUB4",
    type: "buy",
    date: new Date("2024-03-10T10:00:00Z").getTime(),
    quantity: 300,
    pricePerShare: 30.0,
    fees: 0,
    notes: "Aporte",
  },
  {
    id: "tx-itub4-2",
    ticker: "ITUB4",
    type: "buy",
    date: new Date("2024-09-05T10:00:00Z").getTime(),
    quantity: 300,
    pricePerShare: 34.0,
    fees: 0,
    notes: "Aporte",
  },

  // EGIE3 (Qty: 400, PM: 38.0)
  {
    id: "tx-egie3-1",
    ticker: "EGIE3",
    type: "buy",
    date: new Date("2024-04-12T10:00:00Z").getTime(),
    quantity: 200,
    pricePerShare: 36.0,
    fees: 0,
    notes: "Aporte setor elétrico",
  },
  {
    id: "tx-egie3-2",
    ticker: "EGIE3",
    type: "buy",
    date: new Date("2024-10-18T10:00:00Z").getTime(),
    quantity: 200,
    pricePerShare: 40.0,
    fees: 0,
    notes: "Aporte setor elétrico",
  },

  // KNCR11 (Qty: 200, PM: 98.5)
  {
    id: "tx-kncr11-1",
    ticker: "KNCR11",
    type: "buy",
    date: new Date("2024-02-28T10:00:00Z").getTime(),
    quantity: 100,
    pricePerShare: 97.0,
    fees: 0,
    notes: "Alocação FII",
  },
  {
    id: "tx-kncr11-2",
    ticker: "KNCR11",
    type: "buy",
    date: new Date("2024-07-15T10:00:00Z").getTime(),
    quantity: 100,
    pricePerShare: 100.0,
    fees: 0,
    notes: "Alocação FII",
  },

  // MXRF11 (Qty: 3000, PM: 9.8)
  {
    id: "tx-mxrf11-1",
    ticker: "MXRF11",
    type: "buy",
    date: new Date("2024-01-10T10:00:00Z").getTime(),
    quantity: 1500,
    pricePerShare: 9.60,
    fees: 0,
    notes: "Subscrição / Aporte",
  },
  {
    id: "tx-mxrf11-2",
    ticker: "MXRF11",
    type: "buy",
    date: new Date("2024-05-20T10:00:00Z").getTime(),
    quantity: 1500,
    pricePerShare: 10.00,
    fees: 0,
    notes: "Aporte mensal",
  },

  // CPTS11 (Qty: 2500, PM: 8.2)
  {
    id: "tx-cpts11-1",
    ticker: "CPTS11",
    type: "buy",
    date: new Date("2024-03-15T10:00:00Z").getTime(),
    quantity: 1500,
    pricePerShare: 8.00,
    fees: 0,
    notes: "Aporte",
  },
  {
    id: "tx-cpts11-2",
    ticker: "CPTS11",
    type: "buy",
    date: new Date("2024-08-22T10:00:00Z").getTime(),
    quantity: 1000,
    pricePerShare: 8.50,
    fees: 0,
    notes: "Aporte",
  },

  // BDIF11 (Qty: 300, PM: 90.0)
  {
    id: "tx-bdif11-1",
    ticker: "BDIF11",
    type: "buy",
    date: new Date("2024-02-10T10:00:00Z").getTime(),
    quantity: 150,
    pricePerShare: 88.0,
    fees: 0,
    notes: "Aporte Infra",
  },
  {
    id: "tx-bdif11-2",
    ticker: "BDIF11",
    type: "buy",
    date: new Date("2024-07-20T10:00:00Z").getTime(),
    quantity: 150,
    pricePerShare: 92.0,
    fees: 0,
    notes: "Aporte Infra",
  },

  // IFRA11 (Qty: 150, PM: 110.0)
  {
    id: "tx-ifra11-1",
    ticker: "IFRA11",
    type: "buy",
    date: new Date("2024-04-05T10:00:00Z").getTime(),
    quantity: 100,
    pricePerShare: 108.0,
    fees: 0,
    notes: "Aporte Infra",
  },
  {
    id: "tx-ifra11-2",
    ticker: "IFRA11",
    type: "buy",
    date: new Date("2024-09-12T10:00:00Z").getTime(),
    quantity: 50,
    pricePerShare: 114.0,
    fees: 0,
    notes: "Aporte Infra",
  },

  // SNAG11 (Qty: 1000, PM: 10.0)
  {
    id: "tx-snag11-1",
    ticker: "SNAG11",
    type: "buy",
    date: new Date("2024-03-20T10:00:00Z").getTime(),
    quantity: 500,
    pricePerShare: 9.90,
    fees: 0,
    notes: "Aporte Fiagro",
  },
  {
    id: "tx-snag11-2",
    ticker: "SNAG11",
    type: "buy",
    date: new Date("2024-08-15T10:00:00Z").getTime(),
    quantity: 500,
    pricePerShare: 10.10,
    fees: 0,
    notes: "Aporte Fiagro",
  },

  // IVVB11 (Qty: 100, PM: 250.0)
  {
    id: "tx-ivvb11-1",
    ticker: "IVVB11",
    type: "buy",
    date: new Date("2024-01-25T10:00:00Z").getTime(),
    quantity: 50,
    pricePerShare: 240.0,
    fees: 0,
    notes: "Aporte ETF S&P500",
  },
  {
    id: "tx-ivvb11-2",
    ticker: "IVVB11",
    type: "buy",
    date: new Date("2024-06-30T10:00:00Z").getTime(),
    quantity: 50,
    pricePerShare: 260.0,
    fees: 0,
    notes: "Aporte ETF S&P500",
  },

  // O (Qty: 100, PM: 50.0)
  {
    id: "tx-o-1",
    ticker: "O",
    type: "buy",
    date: new Date("2024-02-15T10:00:00Z").getTime(),
    quantity: 50,
    pricePerShare: 48.0,
    fees: 0,
    notes: "US REIT Allocation",
  },
  {
    id: "tx-o-2",
    ticker: "O",
    type: "buy",
    date: new Date("2024-07-10T10:00:00Z").getTime(),
    quantity: 50,
    pricePerShare: 52.0,
    fees: 0,
    notes: "US REIT Allocation",
  },

  // STAG (Qty: 120, PM: 30.0)
  {
    id: "tx-stag-1",
    ticker: "STAG",
    type: "buy",
    date: new Date("2024-03-12T10:00:00Z").getTime(),
    quantity: 60,
    pricePerShare: 29.0,
    fees: 0,
    notes: "US Industrial REIT",
  },
  {
    id: "tx-stag-2",
    ticker: "STAG",
    type: "buy",
    date: new Date("2024-08-18T10:00:00Z").getTime(),
    quantity: 60,
    pricePerShare: 31.0,
    fees: 0,
    notes: "US Industrial REIT",
  },

  // MSFT (Qty: 50, PM: 200.0)
  {
    id: "tx-msft-1",
    ticker: "MSFT",
    type: "buy",
    date: new Date("2024-01-15T10:00:00Z").getTime(),
    quantity: 25,
    pricePerShare: 190.0,
    fees: 0,
    notes: "Tech Core",
  },
  {
    id: "tx-msft-2",
    ticker: "MSFT",
    type: "buy",
    date: new Date("2024-05-10T10:00:00Z").getTime(),
    quantity: 25,
    pricePerShare: 210.0,
    fees: 0,
    notes: "Tech Core",
  },

  // JNJ (Qty: 40, PM: 140.0)
  {
    id: "tx-jnj-1",
    ticker: "JNJ",
    type: "buy",
    date: new Date("2023-01-15T10:00:00Z").getTime(),
    quantity: 20,
    pricePerShare: 135.0,
    fees: 0,
    notes: "Dividend Aristocrat",
  },
  {
    id: "tx-jnj-2",
    ticker: "JNJ",
    type: "buy",
    date: new Date("2023-06-15T10:00:00Z").getTime(),
    quantity: 20,
    pricePerShare: 145.0,
    fees: 0,
    notes: "Dividend Aristocrat",
  },

  // MPW (Qty: 300, PM: 8.0)
  {
    id: "tx-mpw-1",
    ticker: "MPW",
    type: "buy",
    date: new Date("2023-06-20T10:00:00Z").getTime(),
    quantity: 150,
    pricePerShare: 8.5,
    fees: 0,
    notes: "Hospital REIT",
  },
  {
    id: "tx-mpw-2",
    ticker: "MPW",
    type: "buy",
    date: new Date("2023-09-25T10:00:00Z").getTime(),
    quantity: 150,
    pricePerShare: 7.5,
    fees: 0,
    notes: "Hospital REIT",
  },

  // VYM (Qty: 60, PM: 105.0)
  {
    id: "tx-vym-1",
    ticker: "VYM",
    type: "buy",
    date: new Date("2022-04-10T10:00:00Z").getTime(),
    quantity: 30,
    pricePerShare: 100.0,
    fees: 0,
    notes: "High Yield Dividend ETF",
  },
  {
    id: "tx-vym-2",
    ticker: "VYM",
    type: "buy",
    date: new Date("2023-02-15T10:00:00Z").getTime(),
    quantity: 30,
    pricePerShare: 110.0,
    fees: 0,
    notes: "High Yield Dividend ETF",
  },

  // TEST_IPO_RECENTE (Qty: 500, PM: 12.0)
  {
    id: "tx-test-ipo-1",
    ticker: "TEST_IPO_RECENTE",
    type: "buy",
    date: new Date("2024-04-10T10:00:00Z").getTime(),
    quantity: 500,
    pricePerShare: 12.0,
    fees: 0,
    notes: "Oferta Pública Inicial",
  },
];

