import type { WatchlistItem } from "../watchlist";

export const DEV_MOCK_DATA: WatchlistItem[] = [
  // ── ATIVOS ORIGINAIS (8) ────────────────────────────────────────────────────

  {
    id: "brazilian_stock:BBAS3",
    ticker: "BBAS3",
    name: "Banco do Brasil S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 26.5,
    annualDividend: 2.8,
    targetYield: 6,
    ceilingPrice: 46.66,
    safetyMargin: 76.1,
    quantity: 1000,
    averagePrice: 22.0,
    paymentMonths: [2, 3, 5, 6, 8, 9, 11, 12],
    payoutRatio: 40,
    targetMonthlyIncome: 1000,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    id: "brazilian_stock:TEST_IPO_RECENTE",
    ticker: "TEST_IPO_RECENTE",
    name: "Synthetic Recent IPO",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 15.0,
    annualDividend: 1.5,
    targetYield: 6,
    ceilingPrice: 25.0,
    safetyMargin: 66.6,
    quantity: 500,
    averagePrice: 12.0,
    paymentMonths: [4, 10],
    payoutRatio: 50,
    targetMonthlyIncome: 500,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Utilities",
  },
  {
    id: "fii:KNCR11",
    ticker: "KNCR11",
    name: "Kinea Rendimentos Imobiliários",
    type: "FII",
    currency: "BRL",
    currentPrice: 105.0,
    annualDividend: 12.5,
    targetYield: 10,
    ceilingPrice: 125.0,
    safetyMargin: 19.0,
    quantity: 200,
    averagePrice: 98.5,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 500,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    id: "reit:O",
    ticker: "O",
    name: "Realty Income Corporation",
    type: "REIT",
    currency: "USD",
    currentPrice: 55.0,
    annualDividend: 3.1,
    targetYield: 4,
    ceilingPrice: 77.5,
    safetyMargin: 40.9,
    quantity: 100,
    averagePrice: 50.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: 75,
    targetMonthlyIncome: 100,
    addedAt: Date.now(),
    customTaxRate: 30,
    sector: "Real Estate",
  },
  {
    id: "us_stock:MSFT",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    type: "STOCK_US",
    currency: "USD",
    currentPrice: 420.0,
    annualDividend: 3.0,
    targetYield: 2,
    ceilingPrice: 150.0,
    safetyMargin: -64.2,
    quantity: 50,
    averagePrice: 200.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: 25,
    targetMonthlyIncome: 50,
    addedAt: Date.now(),
    customTaxRate: 30,
    sector: "Technology",
  },
  {
    id: "etf:IVVB11",
    ticker: "IVVB11",
    name: "iShares S&P 500 Fundo de Investimento",
    type: "ETF",
    currency: "BRL",
    currentPrice: 280.0,
    annualDividend: 0,
    targetYield: 0,
    ceilingPrice: 0,
    safetyMargin: 0,
    quantity: 100,
    averagePrice: 250.0,
    paymentMonths: [],
    payoutRatio: null,
    targetMonthlyIncome: null,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    id: "fii_infra:BDIF11",
    ticker: "BDIF11",
    name: "BTG Pactual Dívida Infra",
    type: "FII_INFRA",
    currency: "BRL",
    currentPrice: 95.0,
    annualDividend: 12.0,
    targetYield: 11,
    ceilingPrice: 109.09,
    safetyMargin: 14.8,
    quantity: 300,
    averagePrice: 90.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 400,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Infrastructure",
  },
  {
    id: "fiagro:SNAG11",
    ticker: "SNAG11",
    name: "Suno Agro Fiagro",
    type: "FIAGRO",
    currency: "BRL",
    currentPrice: 10.15,
    annualDividend: 1.3,
    targetYield: 12,
    ceilingPrice: 10.83,
    safetyMargin: 6.7,
    quantity: 1000,
    averagePrice: 10.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 150,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Agriculture",
  },

  // ── NOVOS ATIVOS BR (6) — cobre Ação, FII e FII-Infra variados ─────────────

  {
    // Grande ação BR com pagamento semestral concentrado em Jun/Dez.
    // Stresses o gráfico com picos grandes em dois meses específicos.
    id: "brazilian_stock:VALE3",
    ticker: "VALE3",
    name: "Vale S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 62.0,
    annualDividend: 7.8,
    targetYield: 8,
    ceilingPrice: 97.5,
    safetyMargin: 57.3,
    quantity: 800,
    averagePrice: 55.0,
    paymentMonths: [6, 12],
    payoutRatio: 55,
    targetMonthlyIncome: 800,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Materials",
  },
  {
    // Ação BR com pagamento trimestral menos usual (Jan/Abr/Jul/Out).
    // Cria dispersão diferente dos outros ativos trimestrais.
    id: "brazilian_stock:ITUB4",
    ticker: "ITUB4",
    name: "Itaú Unibanco Holding S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 38.5,
    annualDividend: 2.2,
    targetYield: 5,
    ceilingPrice: 44.0,
    safetyMargin: 14.3,
    quantity: 600,
    averagePrice: 32.0,
    paymentMonths: [1, 4, 7, 10],
    payoutRatio: 45,
    targetMonthlyIncome: 300,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    // FII tijolo de alto DY com pagamento mensal. Grande posição para
    // testar dominância no terceiro gráfico (Investido vs. Recebido).
    id: "fii:MXRF11",
    ticker: "MXRF11",
    name: "Maxi Renda FII",
    type: "FII",
    currency: "BRL",
    currentPrice: 10.3,
    annualDividend: 1.44,
    targetYield: 12,
    ceilingPrice: 12.0,
    safetyMargin: 16.5,
    quantity: 3000,
    averagePrice: 9.8,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 360,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    // FII de papel (CRI) com pagamento mensal e yield alto.
    // Segunda maior posição em BRL — boa pressão no top-10.
    id: "fii:CPTS11",
    ticker: "CPTS11",
    name: "Capitânia Securities FII",
    type: "FII",
    currency: "BRL",
    currentPrice: 8.6,
    annualDividend: 1.2,
    targetYield: 13,
    ceilingPrice: 9.23,
    safetyMargin: 7.3,
    quantity: 2500,
    averagePrice: 8.2,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 250,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    // FII-Infra com pagamento mensal e DY elevado.
    // Adiciona diversidade de tipo junto ao BDIF11 já existente.
    id: "fii_infra:IFRA11",
    ticker: "IFRA11",
    name: "iShares Infraestrutura FII",
    type: "FII_INFRA",
    currency: "BRL",
    currentPrice: 118.0,
    annualDividend: 14.4,
    targetYield: 11,
    ceilingPrice: 130.9,
    safetyMargin: 10.9,
    quantity: 150,
    averagePrice: 110.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 200,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Infrastructure",
  },
  {
    // Ação BR de energia com pagamento bianual (Mar/Set).
    // Cria picos de valor real a cada semestre num padrão diferente das anteriores.
    id: "brazilian_stock:EGIE3",
    ticker: "EGIE3",
    name: "Engie Brasil Energia S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 44.0,
    annualDividend: 4.2,
    targetYield: 8,
    ceilingPrice: 52.5,
    safetyMargin: 19.3,
    quantity: 400,
    averagePrice: 38.0,
    paymentMonths: [3, 9],
    payoutRatio: 60,
    targetMonthlyIncome: 200,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Utilities",
  },

  // ── NOVOS ATIVOS US (4) — REITs mensais e ações trimestrais ─────────────────

  {
    // REIT mensal de escritórios — complementa Realty Income na moeda USD.
    // Contribuição mensal estável mas menor que O, gerando mistura de barras.
    id: "reit:STAG",
    ticker: "STAG",
    name: "STAG Industrial REIT",
    type: "REIT",
    currency: "USD",
    currentPrice: 35.0,
    annualDividend: 1.56,
    targetYield: 4.5,
    ceilingPrice: 34.67,
    safetyMargin: -0.9,
    quantity: 120,
    averagePrice: 30.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: 80,
    targetMonthlyIncome: 60,
    addedAt: Date.now(),
    customTaxRate: 30,
    sector: "Real Estate",
  },
  {
    // Blue chip US com DY baixo mas pagamento trimestral consistente.
    // Testa o corte top-10 no terceiro gráfico (investido alto, recebido baixo).
    id: "us_stock:JNJ",
    ticker: "JNJ",
    name: "Johnson & Johnson",
    type: "STOCK_US",
    currency: "USD",
    currentPrice: 155.0,
    annualDividend: 4.76,
    targetYield: 3,
    ceilingPrice: 158.67,
    safetyMargin: 2.4,
    quantity: 40,
    averagePrice: 140.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: 45,
    targetMonthlyIncome: 50,
    addedAt: Date.now(),
    customTaxRate: 30,
    sector: "Healthcare",
  },
  {
    // REIT de saúde — pagamento trimestral, DY razoável.
    // Junto com STAG cria dois tipos de REIT na carteira US.
    id: "reit:MPW",
    ticker: "MPW",
    name: "Medical Properties Trust",
    type: "REIT",
    currency: "USD",
    currentPrice: 5.5,
    annualDividend: 0.6,
    targetYield: 8,
    ceilingPrice: 7.5,
    safetyMargin: 36.4,
    quantity: 300,
    averagePrice: 8.0,
    paymentMonths: [1, 4, 7, 10],
    payoutRatio: 85,
    targetMonthlyIncome: 45,
    addedAt: Date.now(),
    customTaxRate: 30,
    sector: "Real Estate",
  },
  {
    // ETF US de dividendos — pagamento trimestral, exposição ampla.
    // Stresses o gráfico US com um contribuidor menor mas presente em 4 meses.
    id: "etf:VYM",
    ticker: "VYM",
    name: "Vanguard High Dividend Yield ETF",
    type: "ETF",
    currency: "USD",
    currentPrice: 120.0,
    annualDividend: 3.6,
    targetYield: 3,
    ceilingPrice: 120.0,
    safetyMargin: 0.0,
    quantity: 60,
    averagePrice: 105.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: null,
    targetMonthlyIncome: 54,
    addedAt: Date.now(),
    customTaxRate: 30,
    sector: "Diversified",
  },
];
