import type { WatchlistItem } from "../watchlist";

export const DEV_MOCK_DATA: WatchlistItem[] = [
  {
    id: "brazilian_stock:BBAS3",
    ticker: "BBAS3",
    name: "Banco do Brasil S.A.",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 26.5,
    annualDividend: 2.8,
    targetYield: 6,
    ceilingPrice: 46.66,
    safetyMargin: 76.1,
    quantity: 1000,
    averagePrice: 22.0,
    paymentMonths: [2, 3, 5, 6, 8, 9, 11, 12],
    payoutRatio: 40,
    targetMonthlyIncome: 1000,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    id: "brazilian_stock:TEST_IPO_RECENTE",
    ticker: "TEST_IPO_RECENTE",
    name: "Synthetic Recent IPO",
    type: "STOCK_BR",
    currency: "BRL",
    currentPrice: 15.0,
    annualDividend: 1.5,
    targetYield: 6,
    ceilingPrice: 25.0,
    safetyMargin: 66.6,
    quantity: 500,
    averagePrice: 12.0,
    paymentMonths: [4, 10],
    payoutRatio: 50,
    targetMonthlyIncome: 500,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Utilities",
  },
  {
    id: "fii:KNCR11",
    ticker: "KNCR11",
    name: "Kinea Rendimentos Imobiliários",
    type: "FII",
    currency: "BRL",
    currentPrice: 105.0,
    annualDividend: 12.5,
    targetYield: 10,
    ceilingPrice: 125.0,
    safetyMargin: 19.0,
    quantity: 200,
    averagePrice: 98.5,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 500,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Real Estate",
  },
  {
    id: "reit:O",
    ticker: "O",
    name: "Realty Income Corporation",
    type: "REIT",
    currency: "USD",
    currentPrice: 55.0,
    annualDividend: 3.1,
    targetYield: 4,
    ceilingPrice: 77.5,
    safetyMargin: 40.9,
    quantity: 100,
    averagePrice: 50.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: 75,
    targetMonthlyIncome: 100,
    addedAt: Date.now(),
    customTaxRate: 30, // US Tax
    sector: "Real Estate",
  },
  {
    id: "us_stock:MSFT",
    ticker: "MSFT",
    name: "Microsoft Corporation",
    type: "STOCK_US",
    currency: "USD",
    currentPrice: 420.0,
    annualDividend: 3.0,
    targetYield: 2,
    ceilingPrice: 150.0,
    safetyMargin: -64.2, // Overvalued for dividend
    quantity: 50,
    averagePrice: 200.0,
    paymentMonths: [3, 6, 9, 12],
    payoutRatio: 25,
    targetMonthlyIncome: 50,
    addedAt: Date.now(),
    customTaxRate: 30, // US Tax
    sector: "Technology",
  },
  {
    id: "etf:IVVB11",
    ticker: "IVVB11",
    name: "iShares S&P 500 Fundo de Investimento",
    type: "ETF",
    currency: "BRL",
    currentPrice: 280.0,
    annualDividend: 0,
    targetYield: 0,
    ceilingPrice: 0,
    safetyMargin: 0,
    quantity: 100,
    averagePrice: 250.0,
    paymentMonths: [],
    payoutRatio: null,
    targetMonthlyIncome: null,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Financials",
  },
  {
    id: "fii_infra:BDIF11",
    ticker: "BDIF11",
    name: "BTG Pactual Dívida Infra",
    type: "FII_INFRA",
    currency: "BRL",
    currentPrice: 95.0,
    annualDividend: 12.0,
    targetYield: 11,
    ceilingPrice: 109.09,
    safetyMargin: 14.8,
    quantity: 300,
    averagePrice: 90.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 400,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Infrastructure",
  },
  {
    id: "fiagro:SNAG11",
    ticker: "SNAG11",
    name: "Suno Agro Fiagro",
    type: "FIAGRO",
    currency: "BRL",
    currentPrice: 10.15,
    annualDividend: 1.3,
    targetYield: 12,
    ceilingPrice: 10.83,
    safetyMargin: 6.7,
    quantity: 1000,
    averagePrice: 10.0,
    paymentMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    payoutRatio: null,
    targetMonthlyIncome: 150,
    addedAt: Date.now(),
    customTaxRate: null,
    sector: "Agriculture",
  },
];
