/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionTermsRouteImport } from './routes/subscription-terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OnboardingPersonalInfoRouteImport } from './routes/onboarding.personal-info'
import { Route as OnboardingMetasRouteImport } from './routes/onboarding.metas'
import { Route as GuidesDividendValuationRouteImport } from './routes/guides.dividend-valuation'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as AppTaxRouteImport } from './routes/app/tax'
import { Route as AppSnowballeffectsimulatorRouteImport } from './routes/app/snowballeffectsimulator'
import { Route as AppScreenerRouteImport } from './routes/app/screener'
import { Route as AppRiskradarRouteImport } from './routes/app/riskradar'
import { Route as AppReinvestirRouteImport } from './routes/app/reinvestir'
import { Route as AppNewsRouteImport } from './routes/app/news'
import { Route as AppMyportfolioRouteImport } from './routes/app/myportfolio'
import { Route as AppIncomeRouteImport } from './routes/app/income'
import { Route as AppImportBrokerNoteRouteImport } from './routes/app/import-broker-note'
import { Route as AppGoalsRouteImport } from './routes/app/goals'
import { Route as AppGlobalradarRouteImport } from './routes/app/globalradar'
import { Route as AppExploreRouteImport } from './routes/app/explore'
import { Route as AppDocsRouteImport } from './routes/app/docs'
import { Route as AppContributionplanRouteImport } from './routes/app/contributionplan'
import { Route as AppComparatorRouteImport } from './routes/app.comparator'
import { Route as AppAuditRouteImport } from './routes/app/audit'
import { Route as AppAddAssetRouteImport } from './routes/app/add-asset'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionTermsRoute = SubscriptionTermsRouteImport.update({
  id: '/subscription-terms',
  path: '/subscription-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingPersonalInfoRoute = OnboardingPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMetasRoute = OnboardingMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => OnboardingRoute,
} as any)
const GuidesDividendValuationRoute = GuidesDividendValuationRouteImport.update({
  id: '/guides/dividend-valuation',
  path: '/guides/dividend-valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTaxRoute = AppTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => AppRoute,
} as any)
const AppSnowballeffectsimulatorRoute =
  AppSnowballeffectsimulatorRouteImport.update({
    id: '/snowballeffectsimulator',
    path: '/snowballeffectsimulator',
    getParentRoute: () => AppRoute,
  } as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskradarRoute = AppRiskradarRouteImport.update({
  id: '/riskradar',
  path: '/riskradar',
  getParentRoute: () => AppRoute,
} as any)
const AppReinvestirRoute = AppReinvestirRouteImport.update({
  id: '/reinvestir',
  path: '/reinvestir',
  getParentRoute: () => AppRoute,
} as any)
const AppNewsRoute = AppNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppRoute,
} as any)
const AppMyportfolioRoute = AppMyportfolioRouteImport.update({
  id: '/myportfolio',
  path: '/myportfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppIncomeRoute = AppIncomeRouteImport.update({
  id: '/income',
  path: '/income',
  getParentRoute: () => AppRoute,
} as any)
const AppImportBrokerNoteRoute = AppImportBrokerNoteRouteImport.update({
  id: '/import-broker-note',
  path: '/import-broker-note',
  getParentRoute: () => AppRoute,
} as any)
const AppGoalsRoute = AppGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AppRoute,
} as any)
const AppGlobalradarRoute = AppGlobalradarRouteImport.update({
  id: '/globalradar',
  path: '/globalradar',
  getParentRoute: () => AppRoute,
} as any)
const AppExploreRoute = AppExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppContributionplanRoute = AppContributionplanRouteImport.update({
  id: '/contributionplan',
  path: '/contributionplan',
  getParentRoute: () => AppRoute,
} as any)
const AppComparatorRoute = AppComparatorRouteImport.update({
  id: '/comparator',
  path: '/comparator',
  getParentRoute: () => AppRoute,
} as any)
const AppAuditRoute = AppAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppAddAssetRoute = AppAddAssetRouteImport.update({
  id: '/add-asset',
  path: '/add-asset',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/terms': typeof TermsRoute
  '/app/add-asset': typeof AppAddAssetRoute
  '/app/audit': typeof AppAuditRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/contributionplan': typeof AppContributionplanRoute
  '/app/docs': typeof AppDocsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/import-broker-note': typeof AppImportBrokerNoteRoute
  '/app/income': typeof AppIncomeRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/news': typeof AppNewsRoute
  '/app/reinvestir': typeof AppReinvestirRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/app/tax': typeof AppTaxRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/onboarding/metas': typeof OnboardingMetasRoute
  '/onboarding/personal-info': typeof OnboardingPersonalInfoRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/terms': typeof TermsRoute
  '/app/add-asset': typeof AppAddAssetRoute
  '/app/audit': typeof AppAuditRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/contributionplan': typeof AppContributionplanRoute
  '/app/docs': typeof AppDocsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/import-broker-note': typeof AppImportBrokerNoteRoute
  '/app/income': typeof AppIncomeRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/news': typeof AppNewsRoute
  '/app/reinvestir': typeof AppReinvestirRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/app/tax': typeof AppTaxRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/onboarding/metas': typeof OnboardingMetasRoute
  '/onboarding/personal-info': typeof OnboardingPersonalInfoRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/terms': typeof TermsRoute
  '/app/add-asset': typeof AppAddAssetRoute
  '/app/audit': typeof AppAuditRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/contributionplan': typeof AppContributionplanRoute
  '/app/docs': typeof AppDocsRoute
  '/app/explore': typeof AppExploreRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/goals': typeof AppGoalsRoute
  '/app/import-broker-note': typeof AppImportBrokerNoteRoute
  '/app/income': typeof AppIncomeRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/news': typeof AppNewsRoute
  '/app/reinvestir': typeof AppReinvestirRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/app/tax': typeof AppTaxRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/onboarding/metas': typeof OnboardingMetasRoute
  '/onboarding/personal-info': typeof OnboardingPersonalInfoRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/demo'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription-terms'
    | '/terms'
    | '/app/add-asset'
    | '/app/audit'
    | '/app/comparator'
    | '/app/contributionplan'
    | '/app/docs'
    | '/app/explore'
    | '/app/globalradar'
    | '/app/goals'
    | '/app/import-broker-note'
    | '/app/income'
    | '/app/myportfolio'
    | '/app/news'
    | '/app/reinvestir'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/snowballeffectsimulator'
    | '/app/tax'
    | '/app/withdraw'
    | '/guides/dividend-valuation'
    | '/onboarding/metas'
    | '/onboarding/personal-info'
    | '/app/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/demo'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription-terms'
    | '/terms'
    | '/app/add-asset'
    | '/app/audit'
    | '/app/comparator'
    | '/app/contributionplan'
    | '/app/docs'
    | '/app/explore'
    | '/app/globalradar'
    | '/app/goals'
    | '/app/import-broker-note'
    | '/app/income'
    | '/app/myportfolio'
    | '/app/news'
    | '/app/reinvestir'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/snowballeffectsimulator'
    | '/app/tax'
    | '/app/withdraw'
    | '/guides/dividend-valuation'
    | '/onboarding/metas'
    | '/onboarding/personal-info'
    | '/app'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/demo'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription-terms'
    | '/terms'
    | '/app/add-asset'
    | '/app/audit'
    | '/app/comparator'
    | '/app/contributionplan'
    | '/app/docs'
    | '/app/explore'
    | '/app/globalradar'
    | '/app/goals'
    | '/app/import-broker-note'
    | '/app/income'
    | '/app/myportfolio'
    | '/app/news'
    | '/app/reinvestir'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/snowballeffectsimulator'
    | '/app/tax'
    | '/app/withdraw'
    | '/guides/dividend-valuation'
    | '/onboarding/metas'
    | '/onboarding/personal-info'
    | '/app/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionTermsRoute: typeof SubscriptionTermsRoute
  TermsRoute: typeof TermsRoute
  GuidesDividendValuationRoute: typeof GuidesDividendValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-terms': {
      id: '/subscription-terms'
      path: '/subscription-terms'
      fullPath: '/subscription-terms'
      preLoaderRoute: typeof SubscriptionTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/personal-info': {
      id: '/onboarding/personal-info'
      path: '/personal-info'
      fullPath: '/onboarding/personal-info'
      preLoaderRoute: typeof OnboardingPersonalInfoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/metas': {
      id: '/onboarding/metas'
      path: '/metas'
      fullPath: '/onboarding/metas'
      preLoaderRoute: typeof OnboardingMetasRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/guides/dividend-valuation': {
      id: '/guides/dividend-valuation'
      path: '/guides/dividend-valuation'
      fullPath: '/guides/dividend-valuation'
      preLoaderRoute: typeof GuidesDividendValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tax': {
      id: '/app/tax'
      path: '/tax'
      fullPath: '/app/tax'
      preLoaderRoute: typeof AppTaxRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/snowballeffectsimulator': {
      id: '/app/snowballeffectsimulator'
      path: '/snowballeffectsimulator'
      fullPath: '/app/snowballeffectsimulator'
      preLoaderRoute: typeof AppSnowballeffectsimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/screener': {
      id: '/app/screener'
      path: '/screener'
      fullPath: '/app/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/riskradar': {
      id: '/app/riskradar'
      path: '/riskradar'
      fullPath: '/app/riskradar'
      preLoaderRoute: typeof AppRiskradarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reinvestir': {
      id: '/app/reinvestir'
      path: '/reinvestir'
      fullPath: '/app/reinvestir'
      preLoaderRoute: typeof AppReinvestirRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/news': {
      id: '/app/news'
      path: '/news'
      fullPath: '/app/news'
      preLoaderRoute: typeof AppNewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/myportfolio': {
      id: '/app/myportfolio'
      path: '/myportfolio'
      fullPath: '/app/myportfolio'
      preLoaderRoute: typeof AppMyportfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/income': {
      id: '/app/income'
      path: '/income'
      fullPath: '/app/income'
      preLoaderRoute: typeof AppIncomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/import-broker-note': {
      id: '/app/import-broker-note'
      path: '/import-broker-note'
      fullPath: '/app/import-broker-note'
      preLoaderRoute: typeof AppImportBrokerNoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/goals': {
      id: '/app/goals'
      path: '/goals'
      fullPath: '/app/goals'
      preLoaderRoute: typeof AppGoalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/globalradar': {
      id: '/app/globalradar'
      path: '/globalradar'
      fullPath: '/app/globalradar'
      preLoaderRoute: typeof AppGlobalradarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explore': {
      id: '/app/explore'
      path: '/explore'
      fullPath: '/app/explore'
      preLoaderRoute: typeof AppExploreRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contributionplan': {
      id: '/app/contributionplan'
      path: '/contributionplan'
      fullPath: '/app/contributionplan'
      preLoaderRoute: typeof AppContributionplanRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparator': {
      id: '/app/comparator'
      path: '/comparator'
      fullPath: '/app/comparator'
      preLoaderRoute: typeof AppComparatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/audit': {
      id: '/app/audit'
      path: '/audit'
      fullPath: '/app/audit'
      preLoaderRoute: typeof AppAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/add-asset': {
      id: '/app/add-asset'
      path: '/add-asset'
      fullPath: '/app/add-asset'
      preLoaderRoute: typeof AppAddAssetRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAddAssetRoute: typeof AppAddAssetRoute
  AppAuditRoute: typeof AppAuditRoute
  AppComparatorRoute: typeof AppComparatorRoute
  AppContributionplanRoute: typeof AppContributionplanRoute
  AppDocsRoute: typeof AppDocsRoute
  AppExploreRoute: typeof AppExploreRoute
  AppGlobalradarRoute: typeof AppGlobalradarRoute
  AppGoalsRoute: typeof AppGoalsRoute
  AppImportBrokerNoteRoute: typeof AppImportBrokerNoteRoute
  AppIncomeRoute: typeof AppIncomeRoute
  AppMyportfolioRoute: typeof AppMyportfolioRoute
  AppNewsRoute: typeof AppNewsRoute
  AppReinvestirRoute: typeof AppReinvestirRoute
  AppRiskradarRoute: typeof AppRiskradarRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSnowballeffectsimulatorRoute: typeof AppSnowballeffectsimulatorRoute
  AppTaxRoute: typeof AppTaxRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAddAssetRoute: AppAddAssetRoute,
  AppAuditRoute: AppAuditRoute,
  AppComparatorRoute: AppComparatorRoute,
  AppContributionplanRoute: AppContributionplanRoute,
  AppDocsRoute: AppDocsRoute,
  AppExploreRoute: AppExploreRoute,
  AppGlobalradarRoute: AppGlobalradarRoute,
  AppGoalsRoute: AppGoalsRoute,
  AppImportBrokerNoteRoute: AppImportBrokerNoteRoute,
  AppIncomeRoute: AppIncomeRoute,
  AppMyportfolioRoute: AppMyportfolioRoute,
  AppNewsRoute: AppNewsRoute,
  AppReinvestirRoute: AppReinvestirRoute,
  AppRiskradarRoute: AppRiskradarRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSnowballeffectsimulatorRoute: AppSnowballeffectsimulatorRoute,
  AppTaxRoute: AppTaxRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingMetasRoute: typeof OnboardingMetasRoute
  OnboardingPersonalInfoRoute: typeof OnboardingPersonalInfoRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingMetasRoute: OnboardingMetasRoute,
  OnboardingPersonalInfoRoute: OnboardingPersonalInfoRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionTermsRoute: SubscriptionTermsRoute,
  TermsRoute: TermsRoute,
  GuidesDividendValuationRoute: GuidesDividendValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
