/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppV2RouteImport } from './routes/app-v2'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppV2IndexRouteImport } from './routes/app-v2/index'
import { Route as GuidesDividendValuationRouteImport } from './routes/guides.dividend-valuation'
import { Route as AppSnowballeffectsimulatorRouteImport } from './routes/app/snowballeffectsimulator'
import { Route as AppSmartallocationRouteImport } from './routes/app/smartallocation'
import { Route as AppScreenerRouteImport } from './routes/app/screener'
import { Route as AppRiskradarRouteImport } from './routes/app/riskradar'
import { Route as AppMyportfolioRouteImport } from './routes/app/myportfolio'
import { Route as AppGlobalradarRouteImport } from './routes/app/globalradar'
import { Route as AppDocsRouteImport } from './routes/app/docs'
import { Route as AppComparatorRouteImport } from './routes/app.comparator'
import { Route as AppCashflowRouteImport } from './routes/app/cashflow'
import { Route as AppV2ScreenerRouteImport } from './routes/app-v2/screener'
import { Route as AppV2MyportfolioRouteImport } from './routes/app-v2/myportfolio'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppV2Route = AppV2RouteImport.update({
  id: '/app-v2',
  path: '/app-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppV2IndexRoute = AppV2IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppV2Route,
} as any)
const GuidesDividendValuationRoute = GuidesDividendValuationRouteImport.update({
  id: '/guides/dividend-valuation',
  path: '/guides/dividend-valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSnowballeffectsimulatorRoute =
  AppSnowballeffectsimulatorRouteImport.update({
    id: '/snowballeffectsimulator',
    path: '/snowballeffectsimulator',
    getParentRoute: () => AppRoute,
  } as any)
const AppSmartallocationRoute = AppSmartallocationRouteImport.update({
  id: '/smartallocation',
  path: '/smartallocation',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskradarRoute = AppRiskradarRouteImport.update({
  id: '/riskradar',
  path: '/riskradar',
  getParentRoute: () => AppRoute,
} as any)
const AppMyportfolioRoute = AppMyportfolioRouteImport.update({
  id: '/myportfolio',
  path: '/myportfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppGlobalradarRoute = AppGlobalradarRouteImport.update({
  id: '/globalradar',
  path: '/globalradar',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppComparatorRoute = AppComparatorRouteImport.update({
  id: '/comparator',
  path: '/comparator',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)
const AppV2ScreenerRoute = AppV2ScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppV2Route,
} as any)
const AppV2MyportfolioRoute = AppV2MyportfolioRouteImport.update({
  id: '/myportfolio',
  path: '/myportfolio',
  getParentRoute: () => AppV2Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app-v2': typeof AppV2RouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app-v2/myportfolio': typeof AppV2MyportfolioRoute
  '/app-v2/screener': typeof AppV2ScreenerRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/docs': typeof AppDocsRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/smartallocation': typeof AppSmartallocationRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/app-v2/': typeof AppV2IndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app-v2/myportfolio': typeof AppV2MyportfolioRoute
  '/app-v2/screener': typeof AppV2ScreenerRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/docs': typeof AppDocsRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/smartallocation': typeof AppSmartallocationRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/app-v2': typeof AppV2IndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app-v2': typeof AppV2RouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app-v2/myportfolio': typeof AppV2MyportfolioRoute
  '/app-v2/screener': typeof AppV2ScreenerRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/docs': typeof AppDocsRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/smartallocation': typeof AppSmartallocationRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/app-v2/': typeof AppV2IndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app-v2'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/app-v2/myportfolio'
    | '/app-v2/screener'
    | '/app/cashflow'
    | '/app/comparator'
    | '/app/docs'
    | '/app/globalradar'
    | '/app/myportfolio'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/smartallocation'
    | '/app/snowballeffectsimulator'
    | '/guides/dividend-valuation'
    | '/app-v2/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/app-v2/myportfolio'
    | '/app-v2/screener'
    | '/app/cashflow'
    | '/app/comparator'
    | '/app/docs'
    | '/app/globalradar'
    | '/app/myportfolio'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/smartallocation'
    | '/app/snowballeffectsimulator'
    | '/guides/dividend-valuation'
    | '/app-v2'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app-v2'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/app-v2/myportfolio'
    | '/app-v2/screener'
    | '/app/cashflow'
    | '/app/comparator'
    | '/app/docs'
    | '/app/globalradar'
    | '/app/myportfolio'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/smartallocation'
    | '/app/snowballeffectsimulator'
    | '/guides/dividend-valuation'
    | '/app-v2/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AppV2Route: typeof AppV2RouteWithChildren
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  GuidesDividendValuationRoute: typeof GuidesDividendValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-v2': {
      id: '/app-v2'
      path: '/app-v2'
      fullPath: '/app-v2'
      preLoaderRoute: typeof AppV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app-v2/': {
      id: '/app-v2/'
      path: '/'
      fullPath: '/app-v2/'
      preLoaderRoute: typeof AppV2IndexRouteImport
      parentRoute: typeof AppV2Route
    }
    '/guides/dividend-valuation': {
      id: '/guides/dividend-valuation'
      path: '/guides/dividend-valuation'
      fullPath: '/guides/dividend-valuation'
      preLoaderRoute: typeof GuidesDividendValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/snowballeffectsimulator': {
      id: '/app/snowballeffectsimulator'
      path: '/snowballeffectsimulator'
      fullPath: '/app/snowballeffectsimulator'
      preLoaderRoute: typeof AppSnowballeffectsimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smartallocation': {
      id: '/app/smartallocation'
      path: '/smartallocation'
      fullPath: '/app/smartallocation'
      preLoaderRoute: typeof AppSmartallocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/screener': {
      id: '/app/screener'
      path: '/screener'
      fullPath: '/app/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/riskradar': {
      id: '/app/riskradar'
      path: '/riskradar'
      fullPath: '/app/riskradar'
      preLoaderRoute: typeof AppRiskradarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/myportfolio': {
      id: '/app/myportfolio'
      path: '/myportfolio'
      fullPath: '/app/myportfolio'
      preLoaderRoute: typeof AppMyportfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/globalradar': {
      id: '/app/globalradar'
      path: '/globalradar'
      fullPath: '/app/globalradar'
      preLoaderRoute: typeof AppGlobalradarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparator': {
      id: '/app/comparator'
      path: '/comparator'
      fullPath: '/app/comparator'
      preLoaderRoute: typeof AppComparatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashflow': {
      id: '/app/cashflow'
      path: '/cashflow'
      fullPath: '/app/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
    '/app-v2/screener': {
      id: '/app-v2/screener'
      path: '/screener'
      fullPath: '/app-v2/screener'
      preLoaderRoute: typeof AppV2ScreenerRouteImport
      parentRoute: typeof AppV2Route
    }
    '/app-v2/myportfolio': {
      id: '/app-v2/myportfolio'
      path: '/myportfolio'
      fullPath: '/app-v2/myportfolio'
      preLoaderRoute: typeof AppV2MyportfolioRouteImport
      parentRoute: typeof AppV2Route
    }
  }
}

interface AppRouteChildren {
  AppCashflowRoute: typeof AppCashflowRoute
  AppComparatorRoute: typeof AppComparatorRoute
  AppDocsRoute: typeof AppDocsRoute
  AppGlobalradarRoute: typeof AppGlobalradarRoute
  AppMyportfolioRoute: typeof AppMyportfolioRoute
  AppRiskradarRoute: typeof AppRiskradarRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSmartallocationRoute: typeof AppSmartallocationRoute
  AppSnowballeffectsimulatorRoute: typeof AppSnowballeffectsimulatorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashflowRoute: AppCashflowRoute,
  AppComparatorRoute: AppComparatorRoute,
  AppDocsRoute: AppDocsRoute,
  AppGlobalradarRoute: AppGlobalradarRoute,
  AppMyportfolioRoute: AppMyportfolioRoute,
  AppRiskradarRoute: AppRiskradarRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSmartallocationRoute: AppSmartallocationRoute,
  AppSnowballeffectsimulatorRoute: AppSnowballeffectsimulatorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AppV2RouteChildren {
  AppV2MyportfolioRoute: typeof AppV2MyportfolioRoute
  AppV2ScreenerRoute: typeof AppV2ScreenerRoute
  AppV2IndexRoute: typeof AppV2IndexRoute
}

const AppV2RouteChildren: AppV2RouteChildren = {
  AppV2MyportfolioRoute: AppV2MyportfolioRoute,
  AppV2ScreenerRoute: AppV2ScreenerRoute,
  AppV2IndexRoute: AppV2IndexRoute,
}

const AppV2RouteWithChildren = AppV2Route._addFileChildren(AppV2RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AppV2Route: AppV2RouteWithChildren,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  GuidesDividendValuationRoute: GuidesDividendValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
