/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionTermsRouteImport } from './routes/subscription-terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as OnboardingPersonalInfoRouteImport } from './routes/onboarding.personal-info'
import { Route as OnboardingMetasRouteImport } from './routes/onboarding.metas'
import { Route as GuidesDividendValuationRouteImport } from './routes/guides.dividend-valuation'
import { Route as AppSnowballeffectsimulatorRouteImport } from './routes/app/snowballeffectsimulator'
import { Route as AppSmartallocationRouteImport } from './routes/app/smartallocation'
import { Route as AppScreenerRouteImport } from './routes/app/screener'
import { Route as AppRiskradarRouteImport } from './routes/app/riskradar'
import { Route as AppReinvestirRouteImport } from './routes/app/reinvestir'
import { Route as AppRealidadeFiscalRouteImport } from './routes/app/realidade-fiscal'
import { Route as AppMyportfolioRouteImport } from './routes/app/myportfolio'
import { Route as AppMetasRouteImport } from './routes/app/metas'
import { Route as AppGlobalradarRouteImport } from './routes/app/globalradar'
import { Route as AppExplorarRouteImport } from './routes/app/explorar'
import { Route as AppDocsRouteImport } from './routes/app/docs'
import { Route as AppComparatorRouteImport } from './routes/app.comparator'
import { Route as AppCashflowRouteImport } from './routes/app/cashflow'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionTermsRoute = SubscriptionTermsRouteImport.update({
  id: '/subscription-terms',
  path: '/subscription-terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingPersonalInfoRoute = OnboardingPersonalInfoRouteImport.update({
  id: '/personal-info',
  path: '/personal-info',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingMetasRoute = OnboardingMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => OnboardingRoute,
} as any)
const GuidesDividendValuationRoute = GuidesDividendValuationRouteImport.update({
  id: '/guides/dividend-valuation',
  path: '/guides/dividend-valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSnowballeffectsimulatorRoute =
  AppSnowballeffectsimulatorRouteImport.update({
    id: '/snowballeffectsimulator',
    path: '/snowballeffectsimulator',
    getParentRoute: () => AppRoute,
  } as any)
const AppSmartallocationRoute = AppSmartallocationRouteImport.update({
  id: '/smartallocation',
  path: '/smartallocation',
  getParentRoute: () => AppRoute,
} as any)
const AppScreenerRoute = AppScreenerRouteImport.update({
  id: '/screener',
  path: '/screener',
  getParentRoute: () => AppRoute,
} as any)
const AppRiskradarRoute = AppRiskradarRouteImport.update({
  id: '/riskradar',
  path: '/riskradar',
  getParentRoute: () => AppRoute,
} as any)
const AppReinvestirRoute = AppReinvestirRouteImport.update({
  id: '/reinvestir',
  path: '/reinvestir',
  getParentRoute: () => AppRoute,
} as any)
const AppRealidadeFiscalRoute = AppRealidadeFiscalRouteImport.update({
  id: '/realidade-fiscal',
  path: '/realidade-fiscal',
  getParentRoute: () => AppRoute,
} as any)
const AppMyportfolioRoute = AppMyportfolioRouteImport.update({
  id: '/myportfolio',
  path: '/myportfolio',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppGlobalradarRoute = AppGlobalradarRouteImport.update({
  id: '/globalradar',
  path: '/globalradar',
  getParentRoute: () => AppRoute,
} as any)
const AppExplorarRoute = AppExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppComparatorRoute = AppComparatorRouteImport.update({
  id: '/comparator',
  path: '/comparator',
  getParentRoute: () => AppRoute,
} as any)
const AppCashflowRoute = AppCashflowRouteImport.update({
  id: '/cashflow',
  path: '/cashflow',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/terms': typeof TermsRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/docs': typeof AppDocsRoute
  '/app/explorar': typeof AppExplorarRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/metas': typeof AppMetasRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/realidade-fiscal': typeof AppRealidadeFiscalRoute
  '/app/reinvestir': typeof AppReinvestirRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/smartallocation': typeof AppSmartallocationRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/onboarding/metas': typeof OnboardingMetasRoute
  '/onboarding/personal-info': typeof OnboardingPersonalInfoRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/terms': typeof TermsRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/docs': typeof AppDocsRoute
  '/app/explorar': typeof AppExplorarRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/metas': typeof AppMetasRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/realidade-fiscal': typeof AppRealidadeFiscalRoute
  '/app/reinvestir': typeof AppReinvestirRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/smartallocation': typeof AppSmartallocationRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/onboarding/metas': typeof OnboardingMetasRoute
  '/onboarding/personal-info': typeof OnboardingPersonalInfoRoute
  '/app': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/subscription-terms': typeof SubscriptionTermsRoute
  '/terms': typeof TermsRoute
  '/app/cashflow': typeof AppCashflowRoute
  '/app/comparator': typeof AppComparatorRoute
  '/app/docs': typeof AppDocsRoute
  '/app/explorar': typeof AppExplorarRoute
  '/app/globalradar': typeof AppGlobalradarRoute
  '/app/metas': typeof AppMetasRoute
  '/app/myportfolio': typeof AppMyportfolioRoute
  '/app/realidade-fiscal': typeof AppRealidadeFiscalRoute
  '/app/reinvestir': typeof AppReinvestirRoute
  '/app/riskradar': typeof AppRiskradarRoute
  '/app/screener': typeof AppScreenerRoute
  '/app/smartallocation': typeof AppSmartallocationRoute
  '/app/snowballeffectsimulator': typeof AppSnowballeffectsimulatorRoute
  '/guides/dividend-valuation': typeof GuidesDividendValuationRoute
  '/onboarding/metas': typeof OnboardingMetasRoute
  '/onboarding/personal-info': typeof OnboardingPersonalInfoRoute
  '/app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription-terms'
    | '/terms'
    | '/app/cashflow'
    | '/app/comparator'
    | '/app/docs'
    | '/app/explorar'
    | '/app/globalradar'
    | '/app/metas'
    | '/app/myportfolio'
    | '/app/realidade-fiscal'
    | '/app/reinvestir'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/smartallocation'
    | '/app/snowballeffectsimulator'
    | '/guides/dividend-valuation'
    | '/onboarding/metas'
    | '/onboarding/personal-info'
    | '/app/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription-terms'
    | '/terms'
    | '/app/cashflow'
    | '/app/comparator'
    | '/app/docs'
    | '/app/explorar'
    | '/app/globalradar'
    | '/app/metas'
    | '/app/myportfolio'
    | '/app/realidade-fiscal'
    | '/app/reinvestir'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/smartallocation'
    | '/app/snowballeffectsimulator'
    | '/guides/dividend-valuation'
    | '/onboarding/metas'
    | '/onboarding/personal-info'
    | '/app'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/profile'
    | '/settings'
    | '/sitemap.xml'
    | '/subscription-terms'
    | '/terms'
    | '/app/cashflow'
    | '/app/comparator'
    | '/app/docs'
    | '/app/explorar'
    | '/app/globalradar'
    | '/app/metas'
    | '/app/myportfolio'
    | '/app/realidade-fiscal'
    | '/app/reinvestir'
    | '/app/riskradar'
    | '/app/screener'
    | '/app/smartallocation'
    | '/app/snowballeffectsimulator'
    | '/guides/dividend-valuation'
    | '/onboarding/metas'
    | '/onboarding/personal-info'
    | '/app/'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SubscriptionTermsRoute: typeof SubscriptionTermsRoute
  TermsRoute: typeof TermsRoute
  GuidesDividendValuationRoute: typeof GuidesDividendValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription-terms': {
      id: '/subscription-terms'
      path: '/subscription-terms'
      fullPath: '/subscription-terms'
      preLoaderRoute: typeof SubscriptionTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/personal-info': {
      id: '/onboarding/personal-info'
      path: '/personal-info'
      fullPath: '/onboarding/personal-info'
      preLoaderRoute: typeof OnboardingPersonalInfoRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/metas': {
      id: '/onboarding/metas'
      path: '/metas'
      fullPath: '/onboarding/metas'
      preLoaderRoute: typeof OnboardingMetasRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/guides/dividend-valuation': {
      id: '/guides/dividend-valuation'
      path: '/guides/dividend-valuation'
      fullPath: '/guides/dividend-valuation'
      preLoaderRoute: typeof GuidesDividendValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/snowballeffectsimulator': {
      id: '/app/snowballeffectsimulator'
      path: '/snowballeffectsimulator'
      fullPath: '/app/snowballeffectsimulator'
      preLoaderRoute: typeof AppSnowballeffectsimulatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/smartallocation': {
      id: '/app/smartallocation'
      path: '/smartallocation'
      fullPath: '/app/smartallocation'
      preLoaderRoute: typeof AppSmartallocationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/screener': {
      id: '/app/screener'
      path: '/screener'
      fullPath: '/app/screener'
      preLoaderRoute: typeof AppScreenerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/riskradar': {
      id: '/app/riskradar'
      path: '/riskradar'
      fullPath: '/app/riskradar'
      preLoaderRoute: typeof AppRiskradarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reinvestir': {
      id: '/app/reinvestir'
      path: '/reinvestir'
      fullPath: '/app/reinvestir'
      preLoaderRoute: typeof AppReinvestirRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/realidade-fiscal': {
      id: '/app/realidade-fiscal'
      path: '/realidade-fiscal'
      fullPath: '/app/realidade-fiscal'
      preLoaderRoute: typeof AppRealidadeFiscalRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/myportfolio': {
      id: '/app/myportfolio'
      path: '/myportfolio'
      fullPath: '/app/myportfolio'
      preLoaderRoute: typeof AppMyportfolioRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/metas': {
      id: '/app/metas'
      path: '/metas'
      fullPath: '/app/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/globalradar': {
      id: '/app/globalradar'
      path: '/globalradar'
      fullPath: '/app/globalradar'
      preLoaderRoute: typeof AppGlobalradarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/explorar': {
      id: '/app/explorar'
      path: '/explorar'
      fullPath: '/app/explorar'
      preLoaderRoute: typeof AppExplorarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comparator': {
      id: '/app/comparator'
      path: '/comparator'
      fullPath: '/app/comparator'
      preLoaderRoute: typeof AppComparatorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cashflow': {
      id: '/app/cashflow'
      path: '/cashflow'
      fullPath: '/app/cashflow'
      preLoaderRoute: typeof AppCashflowRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCashflowRoute: typeof AppCashflowRoute
  AppComparatorRoute: typeof AppComparatorRoute
  AppDocsRoute: typeof AppDocsRoute
  AppExplorarRoute: typeof AppExplorarRoute
  AppGlobalradarRoute: typeof AppGlobalradarRoute
  AppMetasRoute: typeof AppMetasRoute
  AppMyportfolioRoute: typeof AppMyportfolioRoute
  AppRealidadeFiscalRoute: typeof AppRealidadeFiscalRoute
  AppReinvestirRoute: typeof AppReinvestirRoute
  AppRiskradarRoute: typeof AppRiskradarRoute
  AppScreenerRoute: typeof AppScreenerRoute
  AppSmartallocationRoute: typeof AppSmartallocationRoute
  AppSnowballeffectsimulatorRoute: typeof AppSnowballeffectsimulatorRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashflowRoute: AppCashflowRoute,
  AppComparatorRoute: AppComparatorRoute,
  AppDocsRoute: AppDocsRoute,
  AppExplorarRoute: AppExplorarRoute,
  AppGlobalradarRoute: AppGlobalradarRoute,
  AppMetasRoute: AppMetasRoute,
  AppMyportfolioRoute: AppMyportfolioRoute,
  AppRealidadeFiscalRoute: AppRealidadeFiscalRoute,
  AppReinvestirRoute: AppReinvestirRoute,
  AppRiskradarRoute: AppRiskradarRoute,
  AppScreenerRoute: AppScreenerRoute,
  AppSmartallocationRoute: AppSmartallocationRoute,
  AppSnowballeffectsimulatorRoute: AppSnowballeffectsimulatorRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingMetasRoute: typeof OnboardingMetasRoute
  OnboardingPersonalInfoRoute: typeof OnboardingPersonalInfoRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingMetasRoute: OnboardingMetasRoute,
  OnboardingPersonalInfoRoute: OnboardingPersonalInfoRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SubscriptionTermsRoute: SubscriptionTermsRoute,
  TermsRoute: TermsRoute,
  GuidesDividendValuationRoute: GuidesDividendValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
